-- Reconcile the legacy database with the canonical Prisma schema.
-- Prisma @default(uuid()) is generated by Prisma Client and does not
-- require a PostgreSQL column default for this model.

ALTER TABLE "official_group_receipt_intervals"
ALTER COLUMN "id" DROP DEFAULT;
