-- Migration: add_message_lists (generated by prisma migrate diff)

-- CreateTable
CREATE TABLE "message_lists" (
    "id" UUID NOT NULL,
    "owner_account_id" UUID NOT NULL,
    "name" VARCHAR(200) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "message_lists_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "message_list_members" (
    "id" UUID NOT NULL,
    "list_id" UUID NOT NULL,
    "account_id" UUID,
    "display_name" VARCHAR(250) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "message_list_members_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_folders" (
    "id" UUID NOT NULL,
    "account_id" UUID NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "icon" VARCHAR(50) NOT NULL DEFAULT 'folder',
    "color" VARCHAR(30),
    "position" INTEGER NOT NULL DEFAULT 0,
    "include_private" BOOLEAN NOT NULL DEFAULT false,
    "include_groups" BOOLEAN NOT NULL DEFAULT false,
    "include_official" BOOLEAN NOT NULL DEFAULT false,
    "include_unread_only" BOOLEAN NOT NULL DEFAULT false,
    "exclude_muted" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "chat_folders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_folder_items" (
    "id" UUID NOT NULL,
    "folder_id" UUID NOT NULL,
    "conversation_id" UUID,
    "target_account_id" UUID,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_folder_items_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "message_lists_owner_idx" ON "message_lists"("owner_account_id");

-- CreateIndex
CREATE INDEX "message_list_members_list_idx" ON "message_list_members"("list_id");

-- CreateIndex
CREATE INDEX "chat_folders_account_position_idx" ON "chat_folders"("account_id", "position");

-- CreateIndex
CREATE INDEX "chat_folder_items_folder_idx" ON "chat_folder_items"("folder_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_folder_items_folder_conversation_key" ON "chat_folder_items"("folder_id", "conversation_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_folder_items_folder_target_account_key" ON "chat_folder_items"("folder_id", "target_account_id");

-- AddForeignKey
ALTER TABLE "message_lists" ADD CONSTRAINT "message_lists_owner_account_id_fkey" FOREIGN KEY ("owner_account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "message_list_members" ADD CONSTRAINT "message_list_members_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "message_lists"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "message_list_members" ADD CONSTRAINT "message_list_members_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_folders" ADD CONSTRAINT "chat_folders_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_folder_items" ADD CONSTRAINT "chat_folder_items_folder_id_fkey" FOREIGN KEY ("folder_id") REFERENCES "chat_folders"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_folder_items" ADD CONSTRAINT "chat_folder_items_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_folder_items" ADD CONSTRAINT "chat_folder_items_target_account_id_fkey" FOREIGN KEY ("target_account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
